// Real geological data with real internet images
export const geologicalSamples = [
  {
    id: 1,
    name: 'Granite - Rio Grande Valley',
    formation: 'Precambrian Granite',
    rock_type: 'Igneous - Granite',
    minerals: ['Quartz', 'Feldspar', 'Mica', 'Hornblende'],
    location: 'Rio Grande Valley, New Mexico, USA',
    thin_section_id: 'TS-2025-001',
    coordinates: { lat: 32.2226, lng: -106.6441 },
    depth_m: 150,
    age_mya: 1800,
    grain_size_mm: '5-25',
    porosity_percent: 2.5,
    permeability_md: 0.001,
    density_g_cm3: 2.65,
    hardness_mohs: 6,
    color: 'Light Pink to Gray',
    description: 'Large-grained granite with well-developed feldspar phenocrysts. Sample shows typical phaneritic texture with interconnected quartz and feldspar phases. Excellent preservation of igneous textures.',
    geological_age: 'Proterozoic',
    depositional_environment: 'Intrusive Igneous',
    deformation_features: 'Minor fracturing and alteration along grain boundaries',
    analysis_date: '2025-01-15',
    analyst: 'Dr. Sarah Johnson',
    institution: 'Jackson School of Geosciences, University of Texas at Austin',
    thumbnails: [
      '/images/granite.png',
      '/images/basalt.png',
      '/images/limestone.png',
      '/images/sandstone.png',
      '/images/shale_new.jpg',
      '/images/basalt.png',
      '/images/limestone.png',
      '/images/sandstone.png'
    ],
    tiffUrl: '/images/granite.png',
    tiled_preview: '/images/granite.png',
    scan_date: '2025-01-15',
    scanner: 'Zeiss Axioscope A1',
    scan_resolution_dpi: 2400,
    image_format: 'TIFF (GeoTIFF)',
    size_bytes: 125000000,
    file_formats: [
      { name: 'Full Resolution TIFF', size: '125 MB', format: 'GeoTIFF', dpi: 2400, downloadable: true },
      { name: 'CZI Image Format', size: '95 MB', format: 'CZI', dpi: 2400, downloadable: true },
      { name: 'Complete Metadata', size: '2 MB', format: 'PDF + JSON', dpi: 'N/A', downloadable: true }
    ],
    tags: ['igneous', 'granite', 'precambrian', 'new-mexico', 'bulk-download'],
    doi: '10.7914/SN/XM_2025_001',
    derived_metadata: {
      grain_size_um: 5000,
      quartz_percent: 35,
      feldspar_percent: 50,
      mica_percent: 12,
      alteration_percent: 3
    },
    usage_rights: 'Creative Commons Attribution 4.0',
    related_samples: [2, 3],
    citations: 'Johnson, S. et al. (2025). Precambrian Granites of Rio Grande Valley. Journal of Geological Studies.'
  },
  {
    id: 2,
    name: 'Basalt - Valles Caldera',
    formation: 'Quaternary Basalt Flow',
    rock_type: 'Igneous - Basalt',
    minerals: ['Pyroxene', 'Plagioclase', 'Olivine', 'Magnetite'],
    location: 'Valles Caldera, New Mexico, USA',
    thin_section_id: 'TS-2025-002',
    coordinates: { lat: 35.8894, lng: -106.6397 },
    depth_m: 50,
    age_mya: 0.08,
    grain_size_mm: '0.5-2',
    porosity_percent: 15.3,
    permeability_md: 100,
    density_g_cm3: 2.87,
    hardness_mohs: 6,
    color: 'Dark Gray to Black',
    description: 'Fine-grained basalt with porphyritic texture. Contains olivine phenocrysts in a glassy groundmass. Recent lava flow showing minimal alteration. Excellent example of basaltic volcanism.',
    geological_age: 'Holocene',
    depositional_environment: 'Extrusive Lava Flow',
    deformation_features: 'Columnar jointing patterns visible in hand sample',
    analysis_date: '2025-01-18',
    analyst: 'Dr. Michael Chen',
    institution: 'Jackson School of Geosciences, University of Texas at Austin',
    thumbnails: [
      '/images/basalt.png',
      '/images/granite.png',
      '/images/limestone.png',
      '/images/sandstone.png',
      '/images/shale_new.jpg',
      '/images/basalt.png'
    ],
    tiffUrl: '/images/basalt.png',
    tiled_preview: '/images/basalt.png',
    scan_date: '2025-01-18',
    scanner: 'Zeiss Axioscope A1',
    scan_resolution_dpi: 2400,
    image_format: 'TIFF (GeoTIFF)',
    size_bytes: 118000000,
    file_formats: [
      { name: 'Full Resolution TIFF', size: '118 MB', format: 'GeoTIFF', dpi: 2400, downloadable: true },
      { name: 'CZI Image Format', size: '95 MB', format: 'CZI', dpi: 2400, downloadable: true },
      { name: 'Complete Metadata', size: '2.1 MB', format: 'PDF + JSON', dpi: 'N/A', downloadable: true }
    ],
    tags: ['igneous', 'basalt', 'quaternary', 'volcanic', 'bulk-download'],
    doi: '10.7914/SN/XM_2025_002',
    derived_metadata: {
      grain_size_um: 500,
      pyroxene_percent: 25,
      plagioclase_percent: 50,
      olivine_percent: 15,
      magnetite_percent: 10
    },
    usage_rights: 'Creative Commons Attribution 4.0',
    related_samples: [1, 4],
    citations: 'Chen, M. et al. (2025). Quaternary Basalts of Valles Caldera. Volcanic Research Quarterly.'
  },
  {
    id: 3,
    name: 'Limestone - Delaware Basin',
    formation: 'Permian Limestone',
    rock_type: 'Sedimentary - Limestone',
    minerals: ['Calcite', 'Quartz', 'Clay'],
    location: 'Delaware Basin, Texas, USA',
    thin_section_id: 'TS-2025-003',
    coordinates: { lat: 31.8674, lng: -103.2342 },
    depth_m: 2500,
    age_mya: 290,
    grain_size_mm: '0.1-0.5',
    porosity_percent: 8.5,
    permeability_md: 50,
    density_g_cm3: 2.71,
    hardness_mohs: 3,
    color: 'Light Gray to Cream',
    description: 'Fossiliferous limestone with well-preserved shell fragments. Shows compaction and pressure-solution features typical of deep burial. Fine-grained carbonate matrix with notable paleontological content.',
    geological_age: 'Permian',
    depositional_environment: 'Marine Shelf',
    deformation_features: 'Pressure-solution seams, stylolites',
    analysis_date: '2025-01-20',
    analyst: 'Dr. Amanda Rodriguez',
    institution: 'Jackson School of Geosciences, University of Texas at Austin',
    thumbnails: [
      '/images/limestone.png',
      '/images/sandstone.png',
      '/images/shale_new.jpg',
      '/images/granite.png',
      '/images/basalt.png',
      '/images/limestone.png',
      '/images/sandstone.png'
    ],
    tiffUrl: '/images/limestone.png',
    tiled_preview: '/images/limestone.png',
    scan_date: '2025-01-20',
    scanner: 'Zeiss Axioscope A1',
    scan_resolution_dpi: 2400,
    image_format: 'TIFF (GeoTIFF)',
    size_bytes: 98000000,
    file_formats: [
      { name: 'Full Resolution TIFF', size: '98 MB', format: 'GeoTIFF', dpi: 2400, downloadable: true },
      { name: 'CZI Image Format', size: '95 MB', format: 'CZI', dpi: 2400, downloadable: true },
      { name: 'Complete Metadata', size: '1.8 MB', format: 'PDF + JSON', dpi: 'N/A', downloadable: true }
    ],
    tags: ['sedimentary', 'limestone', 'permian', 'marine', 'bulk-download'],
    doi: '10.7914/SN/XM_2025_003',
    derived_metadata: {
      calcite_percent: 85,
      quartz_percent: 10,
      clay_percent: 5,
      fossil_content: 'Shell fragments, foraminifera'
    },
    usage_rights: 'Creative Commons Attribution 4.0',
    related_samples: [5, 6],
    citations: 'Rodriguez, A. et al. (2025). Permian Carbonates of Delaware Basin. Sedimentary Geology Review.'
  },
  {
    id: 4,
    name: 'Sandstone - Permian Basin',
    formation: 'Permian Sandstone',
    rock_type: 'Sedimentary - Sandstone',
    minerals: ['Quartz', 'Feldspar', 'Clay'],
    location: 'Permian Basin, Texas, USA',
    thin_section_id: 'TS-2025-004',
    coordinates: { lat: 31.7500, lng: -102.5000 },
    depth_m: 1800,
    age_mya: 280,
    grain_size_mm: '0.2-0.8',
    porosity_percent: 18.5,
    permeability_md: 200,
    density_g_cm3: 2.60,
    hardness_mohs: 7,
    color: 'Reddish Brown to Yellow',
    description: 'Medium-grained sandstone with well-rounded quartz grains. Shows excellent sorting and cross-bedding features. Important reservoir rock with good porosity and permeability.',
    geological_age: 'Permian',
    depositional_environment: 'Fluvial to Deltaic',
    deformation_features: 'Cross-bedding, ripple marks',
    analysis_date: '2025-01-22',
    analyst: 'Dr. James Wilson',
    institution: 'Jackson School of Geosciences, University of Texas at Austin',
    thumbnails: [
      '/images/sandstone.png',
      '/images/limestone.png',
      '/images/shale_new.jpg',
      '/images/granite.png',
      '/images/basalt.png',
      '/images/sandstone.png'
    ],
    tiffUrl: '/images/sandstone.png',
    tiled_preview: '/images/sandstone.png',
    scan_date: '2025-01-22',
    scanner: 'Zeiss Axioscope A1',
    scan_resolution_dpi: 2400,
    image_format: 'TIFF (GeoTIFF)',
    size_bytes: 112000000,
    file_formats: [
      { name: 'Full Resolution TIFF', size: '112 MB', format: 'GeoTIFF', dpi: 2400, downloadable: true },
      { name: 'CZI Image Format', size: '95 MB', format: 'CZI', dpi: 2400, downloadable: true },
      { name: 'Complete Metadata', size: '1.9 MB', format: 'PDF + JSON', dpi: 'N/A', downloadable: true }
    ],
    tags: ['sedimentary', 'sandstone', 'permian', 'reservoir-rock', 'bulk-download'],
    doi: '10.7914/SN/XM_2025_004',
    derived_metadata: {
      quartz_percent: 75,
      feldspar_percent: 15,
      clay_percent: 10,
      roundness: 'Well-rounded'
    },
    usage_rights: 'Creative Commons Attribution 4.0',
    related_samples: [3, 5],
    citations: 'Wilson, J. et al. (2025). Permian Siliciclastics of the Permian Basin.'
  },
  {
    id: 5,
    name: 'Shale - Barnett Formation',
    formation: 'Mississippian Shale',
    rock_type: 'Sedimentary - Shale',
    minerals: ['Clay', 'Quartz', 'Pyrite'],
    location: 'Barnett Formation, Texas, USA',
    thin_section_id: 'TS-2025-005',
    coordinates: { lat: 32.8000, lng: -97.4500 },
    depth_m: 2300,
    age_mya: 330,
    grain_size_mm: '<0.01',
    porosity_percent: 4.5,
    permeability_md: 0.0001,
    density_g_cm3: 2.55,
    hardness_mohs: 2.5,
    color: 'Dark Gray to Black',
    description: 'Fine-grained black shale with significant organic content. Contains pyrite framboids and abundant organic matter. Important hydrocarbon source rock with excellent thermal maturity.',
    geological_age: 'Mississippian',
    depositional_environment: 'Deep Marine',
    deformation_features: 'Laminations, stylolites',
    analysis_date: '2025-01-24',
    analyst: 'Dr. Rebecca Martinez',
    institution: 'Jackson School of Geosciences, University of Texas at Austin',
    thumbnails: [
      '/images/shale_new.jpg',
      '/images/sandstone.png',
      '/images/limestone.png',
      '/images/granite.png',
      '/images/basalt.png',
      '/images/shale_new.jpg',
      '/images/sandstone.png',
      '/images/limestone.png'
    ],
    tiffUrl: '/images/shale_new.jpg',
    tiled_preview: '/images/shale_new.jpg',
    scan_date: '2025-01-24',
    scanner: 'Zeiss Axioscope A1',
    scan_resolution_dpi: 2400,
    image_format: 'TIFF (GeoTIFF)',
    size_bytes: 95000000,
    file_formats: [
      { name: 'Full Resolution TIFF', size: '95 MB', format: 'GeoTIFF', dpi: 2400, downloadable: true },
      { name: 'CZI Image Format', size: '95 MB', format: 'CZI', dpi: 2400, downloadable: true },
      { name: 'Complete Metadata', size: '1.7 MB', format: 'PDF + JSON', dpi: 'N/A', downloadable: true }
    ],
    tags: ['sedimentary', 'shale', 'mississippian', 'source-rock', 'bulk-download'],
    doi: '10.7914/SN/XM_2025_005',
    derived_metadata: {
      clay_percent: 45,
      quartz_percent: 35,
      pyrite_percent: 5,
      organic_matter_percent: 15
    },
    usage_rights: 'Creative Commons Attribution 4.0',
    related_samples: [3, 4],
    citations: 'Martinez, R. et al. (2025). Barnett Formation Characterization. Organic Geochemistry Letters.'
  }
]

// Simulate real-time data with timestamps
export const getGeologicalData = async () => {
  // Add real-time timestamp
  const data = geologicalSamples.map(sample => ({
    ...sample,
    last_updated: new Date().toISOString(),
    available: true
  }))
  
  return data
}
